BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'horizontal'
        Slider:
            min: 0
            max: 255
            step: 1
            orientation: 'vertical'
            cursor_size: (0, 0)
            value_track: True
            value_track_color: [0, 0, 255, 1]
        SampleSlider
    BoxLayout:
        orientation: 'horizontal'
        Button:
            text: 'Connect'
        Button:
            text: 'Send'
