BoxLayout:
    orientation: 'vertical'
    SampleSlider:
        id: samples
        num_sliders: 16
        size: (400, 100)
    BoxLayout:
        orientation: 'horizontal'
        size_hint: (1, 0.25)
        Button:
            text: 'Connect'
            on_press: app.connect()
        Button:
            text: 'Send'
            on_press: app.send(bytearray([0xfe, 0xae, 0x4f, 0x51]))
    Label:
        text: app.status
        size_hint: (1, 0.1)
